[ui]
use_nerd_font_icons = true
show_help_bar = false


[keybindings.Channel]
select_next_entry = "ctrl-n"
select_prev_entry = "ctrl-p"


[keybindings.RemoteControl]
select_next_entry = "ctrl-n"
select_prev_entry = "ctrl-p"


[keybindings.SendToChannel]
select_next_entry = "ctrl-n"
select_prev_entry = "ctrl-p"
