# Global configuration file to be shared across machines

[settings]
experimental = true
default_config_filename = ".mise.toml"

[tools]
node = ["lts", "20", "18"]
python = ["latest", "3.12", "3.11"]
