# Global configuration file to be shared across machines

[settings]
experimental = true

[tools]
erlang = "latest"
go = "latest"
lua = "latest"
node = ["lts", "20", "18"]
python = ["latest", "3.12", "3.11"]
ruby = "latest"
