#!/usr/bin/env bash

mkdir -p "$XDG_CONFIG_HOME/mise"
mkdir -p "$XDG_CONFIG_HOME/mise/conf.d"

ln -sfn "$DOTFILES/mise/all.toml" "$XDG_CONFIG_HOME/mise/config.toml"

OS="$(uname -s)"

case $OS in
Darwin)
  if [ -f "$DOTFILES/mise/mac.toml" ]; then
    ln -sfn "$DOTFILES/mise/mac.toml" "$XDG_CONFIG_HOME/mise/conf.d/mac.toml"
  fi
  ;;

Linux)

  # Use os-release file when possible.
  if [[ -f /etc/os-release ]]; then
    . /etc/os-release

    case $ID in
    ubuntu)
      if [ -f "$DOTFILES/mise/ubuntu.toml" ]; then
        ln -sfn "$DOTFILES/mise/ubuntu.toml" "$XDG_CONFIG_HOME/mise/conf.d/ubuntu.toml"
      fi

      # WARN:
      # do I want to be installing software here?
      # Is this just for symlinking files?
      # Is this now becoming more bootstrappy?

      # install dependencies:

      # ruby build
      # sudo apt-get install autoconf patch build-essential rustc libssl-dev \
      #   libyaml-dev libreadline6-dev zlib1g-dev libgmp-dev libncurses5-dev \
      #   libffi-dev libgdbm6 libgdbm-dev libdb-dev uuid-dev -y

      # lua
      # sudo apt-get install unzip -y
      ;;
    esac
  fi

  # TODO: distinguish between different types of Linux when /etc/os-release doesn't exist

  ;;
esac
