let mapleader = " "

set number
set relativenumber

set autoindent
set smartindent " I may remove this.
set expandtab
set shiftwidth=2
set tabstop=2
set smarttab
set shiftround

set nowrap

set splitbelow
set splitright

" Use Kitty keyboard protocol for Ghostty.
set keyprotocol=ghostty:kitty

" Split below.
nnoremap <leader>- <C-w>s

" Split right.
nnoremap <leader><Bar> <C-w>v

" Focus left pane.
nnoremap <C-h> <C-w>h

" Focus lower pane.
nnoremap <C-j> <C-w>j

" Focus upper pane.
nnoremap <C-k> <C-w>k

" Focus right pane.
nnoremap <C-l> <C-w>l

" Open file explorer.
nnoremap - <cmd>Explore<cr>

syntax on

colorscheme habamax
