#!/usr/bin/env bash

# Logging options.
: "${ENABLE_COLOR:=1}" # 1 = colored output,      0 = plain
: "${ENABLE_DEBUG:=0}" # 1 = show debug messages, 0 = hide
DATE_FORMAT="%Y-%m-%d %H:%M:%S"

# ANSI color codes.
RESET="\e[0m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
CYAN="\e[36m"

################################################################################
# LOGGING
################################################################################

########################################
# Internal logging function. Should not be called directly. See wrappers below.
# Globals:
#   DATE_FORMAT
#   ENABLE_COLOR
#   RESET
# Arguments:
#   Log level, a string, all caps.
#   Message to be logged.
#   Color to be used, ANSI escape sequence.
#   (Optional) File descriptor to write to, an integer. Defaults to 1 (stdout).
# Outputs:
#   Writes message to file descriptor.
########################################
_log() {
  local level=$1
  local msg=$2
  local color=$3
  local fd=${4:-1}
  local timestamp
  timestamp=$(date +"$DATE_FORMAT")

  if [[ $ENABLE_COLOR -eq 1 && -n "$color" ]]; then
    printf "%s ${color}[%-7s]${RESET} %s\n" "$timestamp" "$level" "$msg" >&"$fd"
  else
    printf "%s [%-7s] %s\n" "$timestamp" "$level" "$msg" >&"$fd"
  fi
}

########################################
# Write an information message to stdout.
# Globals:
#   BLUE
# Arguments:
#   Message to be logged.
# Outputs:
#   Writes message to stdout.
########################################
info() { _log "INFO" "$1" "$BLUE"; }

########################################
# Write a warning message to stderr.
# Globals:
#   YELLOW
# Arguments:
#   Message to be logged.
# Outputs:
#   Writes message to stderr.
########################################
warn() { _log "WARN" "$1" "$YELLOW" 2; }

########################################
# Write an error message to stderr. This should be used when an unrecoverable
# error occurs and execution should terminate.
# Globals:
#   RED
# Arguments:
#   Message to be logged.
# Outputs:
#   Writes message to stderr.
# Returns:
#   1 to indicate that an error has occurred.
########################################
error() {
  _log "ERROR" "$1" "$RED" 2
  return 1
}

########################################
# Write a success message to stdout.
# Globals:
#   GREEN
# Arguments:
#   Message to be logged.
# Outputs:
#   Writes message to stdout.
########################################
success() { _log "SUCCESS" "$1" "$GREEN"; }

########################################
# Write a debug message to stderr if ENABLE_DEBUG=1.
# Globals:
#   ENABLE_DEBUG
#   CYAN
# Arguments:
#   Message to be logged.
# Outputs:
#   Writes message to stderr if ENABLE_DEBUG=1.
########################################
debug() { if [[ $ENABLE_DEBUG -eq 1 ]]; then _log "DEBUG" "$1" "$CYAN" 2; fi; }

########################################
# Check if a command exists.
# Arguments:
#   Command to check.
# Returns:
#   0 if command exists, 1 otherwise.
########################################
available() {
  command -v -- "$1" &>/dev/null
}

########################################
# Check if a command does not exist.
# Arguments:
#   Command to check.
# Returns:
#   0 if command does not exist, 1 otherwise.
########################################
unavailable() {
  ! available "$1"
}

########################################
# Check if a command exists and log an error if it does not.
# Use this when a command not existing is an unrecoverable error.
# Ensure `set -e` is enabled otherwise you are respobsible for exiting if this
# function returns 1.
# Arguments:
#   Command to check.
# Outputs:
#   Message to stderr if command does not exist.
# Returns:
#   0 if command exists, 1 otherwise.
########################################
need() {
  local cmd=$1

  available "$cmd" || error "Needs $cmd"
}

########################################
# Check if a file is a regular executable file.
# Arguments:
#   File to check, a path.
# Returns:
#   0 if file is a regular executable file, 1 otherwise.
########################################
is_executable_file() {
  local file=$1

  [[ -f $file && -x $file ]]
}
