#!/usr/bin/env bash

source "$DOTFILES"/zsh/env/non-interactive

mkdir -p "$ZDOTDIR"
mkdir -p "$ZSH_COMPLETIONS"

ln -sfn "$DOTFILES/zsh/zshenv" "$HOME/.zshenv"
ln -sfn "$DOTFILES/zsh/zshrc" "$ZDOTDIR/.zshrc"
ln -sfn "$DOTFILES/zsh/zprofile" "$ZDOTDIR/.zprofile"
