#!/usr/bin/env zsh

OS="$(uname -s)"

if [[ $OS == "Darwin" ]]; then
  # homebrew
  eval "$(/opt/homebrew/bin/brew shellenv)"

  # jetbrains toolbox
  path+=("$HOME/Library/Application Support/JetBrains/Toolbox/scripts")
fi

# WARN: when installing JetBrains Toolbox, it will likely try to append a PATH
# modification below this. This is unnecessary and should be removed after it
# has been installed.
