# DO NOT set PATH in this file: https://gist.github.com/Linerre/f11ad4a6a934dcf01ee8415c9457e7b2
# Use $ZDOTDIR/.zshrc instead

# dotfiles
export DOTFILES="$HOME/.dotfiles"

# development
export DEVELOPER="$HOME/Developer"

# xdg
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_DIRS="/usr/local/share:/usr/share"
export XDG_CONFIG_DIRS="/etc/xdg"

# terminal
export DESIRED_TERM_PROGRAM="WezTerm"

# editor
export EDITOR="nvim"
export VISUAL="nvim"
export NVIM_APPNAME="peter.nvim"

# browser
export BROWSER="Brave Browser"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH_COMPLETIONS="$XDG_DATA_HOME/zsh/completions"

# starship prompt
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"

# gamon
export GAM_REPO_ROOT_DIR="$DEVELOPER"

# gh cli
export GH_CONFIG_DIR="$XDG_CONFIG_HOME/gh"
