# TODO: use zinit ???
# this would be primarily for installing plugins
# which would make this config less reliant on a
# platform specific package manager, thus making
# this config more portable.

# define directory for zsh config files
zsh_conf_dir="$HOME/.zshrc.d"

# names of config scripts
zsh_conf_scripts=(
  "environment" # general environment variables
  "languages"   # language-specific environment variables
  "nvm"         # set up node version manager
  "gamon"       # start gamon
  "functions"   # functions
  "aliases"     # aliases
  "completion"  # shell completion
  "starship"    # starship terminal prompt
  "sdkman"      # initialise sdkman
  "zsh-plugins" # enable zsh plugins (must go last)
)

# source config scripts
for conf_script in "${zsh_conf_scripts[@]}"; do
  source "$zsh_conf_dir/$conf_script.sh"
done

# ensure correct gh account on startup
gh_auth_switch_on_pwd

# TODO: move this into a file in "$HOME/.zshrc.d"
#
# ensure git-scripts are in PATH
export PATH="$PATH:$HOME/.git-scripts"

# TODO: move this into a file in "$HOME/.zshrc.d"
#
# ensure user-specific scripts and executables are in PATH
export PATH="$PATH:$HOME/.local/bin"

# TODO: move this into a file in "$HOME/.zshrc.d"
#
# keybinds
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

# fuzzy finding
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}' # case insensitive completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'colorls --color=always $realpath'

# TODO: move this into a file in "$HOME/.zshrc.d"
#
# History commands:
# -----------------
setopt hist_ignore_space    # Commands not saved if they are prepended with a space
setopt hist_ignore_all_dups # Remove all duplicate commands from history
setopt hist_save_no_dups    # Do not write duplicate commands to history file
setopt hist_ignore_dups     # Ignore duplicate commands in history
setopt hist_find_no_dups    # Do not display duplicate commands during history search

# yazi
function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(cat -- "$tmp")" && [ "$cwd" != "" ] && [ "$cwd" != "$PWD" ]; then
    cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}

# automatically launch tmux session if not already in one.
# I won't use this until I've properly configured tmux.
# if [ -z "$TMUX" ]; then
#   tmux
# fi

alias so="source"

# this doesn't have any functionality yet
# alias f='find ~ ~/Developer/peter-bread ~/Developer/ak22112 ~/.config -mindepth 1 -maxdepth 1 -type d | sed "s|$HOME|~|g" | fzf'

# rename() {
#   $HOME/.dotfiles/rename.sh $@
#}


# source "$DOTFILES/cli_stow.sh"
