#!/usr/bin/env bash

mkdir -p "$XDG_CONFIG_HOME/ghostty"

ln -sfn "$DOTFILES/ghostty/config" "$XDG_CONFIG_HOME/ghostty/config"

ln -sfn "$DOTFILES/ghostty/shaders" "$XDG_CONFIG_HOME/ghostty/shaders"

OS="$(uname -s)"

case $OS in
Darwin)
  [ -f "$DOTFILES/ghostty/mac" ] &&
    ln -sfn "$DOTFILES/ghostty/mac" "$XDG_CONFIG_HOME/ghostty/mac"
  ;;
esac
