#!/usr/bin/env bash

mkdir -p "$HOME/.local/bin"

while IFS= read -r -d '' file; do
  [[ -x "$file" ]] || continue
  ln -sfn "$file" "$HOME/.local/bin/$(basename "$file")"
done < <(find "$DOTFILES/scripts" -type f ! -name '*.md' -print0)
