#!/usr/bin/env bash

# PATH ========================================================================

# Git scripts (add custom git commands)
# path+=("$DOTFILES/git/git-scripts")

# Languages -------------------------------------------------------------------

[ -d "$(brew --prefix ruby)/bin" ] && PATH="$(brew --prefix ruby)/bin:$PATH"

[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env"

[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] &&
  source "$HOME/.sdkman/bin/sdkman-init.sh"

# Mise-en-place ---------------------------------------------------------------

if command -v mise &>/dev/null; then
  eval "$(mise activate bash)"    # Interactive Usage
  eval "$(mise hook-env -s bash)" # Usage in this script
fi

# General ---------------------------------------------------------------------

# User-specific scripts and executables
mkdir -p "$HOME/.local/bin"
PATH="$HOME/.local/bin:$PATH"

# Starship Prompt =============================================================

if command -v starship &>/dev/null; then
  eval "$(starship init bash)"
fi

# GH CLI ======================================================================

if command -v gamon3 &>/dev/null; then
  eval "$(gamon3 hook bash)"
fi

if [[ -s $HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh ]]; then
  . "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"
fi

# Browser =====================================================================

case $(uname -s) in
Darwin)
  # Actual default browser must be set manually:
  # System Settings -> Desktop & Dock -> Default Web Browser
  export BROWSER="open"
  ;;
esac
