---
name: Check Generated

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: make update-generated # Checks all generated content in a single step.
      - run: git diff --exit-code
